### ISSUE TITLE
Setup nsqd and nsqlookupd

### ISSUE THREAD

**Issue by GeertJohan** [nulpunt/systems#14]
Please download and setup nsqd and nsqlookupd with proper service scripts and flags.
These only need to communicate on localhost for now.

Optionally, if you feel like it, setup nsqadmin to listen on localhost. It does not provide authentication so we'll use socks to make http requests.

http://bitly.github.io/nsq/overview/quick_start.html

http://bitly.github.io/nsq/deployment/production.html

**Comment by pgodschalk** [comment]
Why.

**Comment by GeertJohan** [comment]
cuz we need its for dispatiching messages from one app to other app

**Comment by GeertJohan** [comment]
Contrary to earlier provided information; please setup both `nslookupd` and `nsqd` to run as a service. `nsqd` should use the `nsqlookupd` instance that is running localhost. Both processes should only listen for localhost connections for now (nightly and alpha).

**Comment by pgodschalk** [comment]
Superceded by #15

**Comment by GeertJohan** [comment]
This is still required. For instance the ocr jobs queue. and likely other jobs.
