### ISSUE TITLE
Manually merge /etc/default/jenkins with upstream changes

### ISSUE THREAD

**Issue by pgodschalk** [nulpunt/systems#18]
--- /etc/default/jenkins        2013-09-20 23:51:42.294893335 +0200
+++ /etc/default/jenkins.dpkg-new       2014-01-13 17:08:19.000000000 +0100
@@ -7,6 +7,7 @@
 JAVA=/usr/bin/java

 # arguments to pass to java
+JAVA_ARGS="-Djava.awt.headless=true"  # Allow graphs etc. to work even when an 
X server is present
 #JAVA_ARGS="-Xmx256m"
 #JAVA_ARGS="-Djava.net.preferIPv4Stack=true" # make jenkins listen on IPv4 addr
ess

@@ -38,12 +39,10 @@
 MAXOPENFILES=8192

 # port for HTTP connector (default 8080; disable with -1)
-HTTP_PORT=-1
-HTTPS_PORT=-1
+HTTP_PORT=8080

 # port for AJP connector (disabled by default)
-AJP_ADDRESS=127.0.0.1
-AJP_PORT=8102
+AJP_PORT=-1

 # servlet context, important if you want to use apache proxying  
 PREFIX=/jenkins
@@ -58,4 +57,4 @@
 # --webroot=~/.jenkins/war
 # --prefix=$PREFIX

-JENKINS_ARGS="--webroot=/var/cache/jenkins/war --httpPort=$HTTP_PORT --httpsPort=$HTTPS_PORT --ajp13ListenAddress=$AJP_ADDRESS --ajp13Port=$AJP_PORT"
+JENKINS_ARGS="--webroot=/var/cache/jenkins/war --httpPort=$HTTP_PORT --ajp13Port=$AJP_PORT"

**Comment by GeertJohan** [comment]
Don't. Just keep /etc/default/jenkins

You could add `+JAVA_ARGS="-Djava.awt.headless=true" # Allow graphs etc. to work even when an
X server is present`, even though it has no effects for us. But all other changes are wrong and will break our jenkins setup.

**Comment by pgodschalk** [comment]
I know it is, but the java args still need to be merged for compatibility with future upstream versions.
