### ISSUE TITLE
Setting up hardware and installing server OS

### ISSUE THREAD

**Issue by GeertJohan** [nulpunt/systems#2]
Setup the server with Debian. Preferably use RAID1 and FDE.

**Comment by GeertJohan** [comment]
We've had troubles with setting up the server.
@Argure will try again today. We might drop FDE and/or RAID1 in favor of development speed for the beta. (No-one should assume the beta is completely data-safe anyway, that's why it's called a beta). When dropping RAID1, we'll have to install some system to make timed backups of the datasets.

Notify @yjb81 @R41M

**Comment by GeertJohan** [comment]
Dropped RAID-1. It makes the setup imposible. We'll have to do manual data-backups.

**Comment by GeertJohan** [comment]
Server installed.

**Comment by pgodschalk** [comment]
RAID-1 is dropped, would only work as software RAID. Mounted `/dev/sda` (500 GB) as `/backup`.
